import * as $ from 'jquery';
export const Client = [
    {
        id: '0',
        videoUrl: '../../../assets/videos/espressoSpot.mp4',
        profilePicture: '../../../assets/images/negociostegus/espresso.jpg',
        postLikes: '427.9K',
        isLike: false,
        postComments: '2051',
        postUserName: 'espresso',
        postDescription: 'Espresso Americano #cafe',
        postSongName: 'Espresso Americano Spot',
        postSongImage: '../../../assets/images/worldIcon.png',
        isPlay: true,
        clientTikTok: "https://www.tiktok.com/@espressoamericanohn",
        clientFollowers: 300000,
        clientFollowing: 18000,
        clientLocation: "Mall Cascadas",
        clientLatitude: 0,
        clientlongitude: 0,
        clientPhoneNumber:'98989999',
        clientEmail:'a@b.com'
    },

    {
        id: '1',
        videoUrl: '../../../assets/videos/roadView.mp4',
        profilePicture: '../../../assets/images/negociostegus/lafinca.jpg',
        postLikes: '900.9K',
        isLike: true,
        postComments: '15K',
        postUserName: 'lafinca',
        postDescription: 'Restaurante La Finca #delicioso',
        postSongName: 'R10 - Oboy',
        postSongImage: '../../../assets/images/worldIcon.png',
        isPlay: true,
        clientTikTok: "https://www.tiktok.com/@lafincahn",
        clientFollowers: 150000,
        clientFollowing: 9000,
        clientLocation: "Santa Rosa De Copan",
        clientLatitude: 0,
        clientlongitude: 0,
        clientPhoneNumber:'98989999',
        clientEmail:'a@b.com'
    },

    {
        id: '2',
        videoUrl: '../../../assets/videos/Ciudad/Tegucigalpa-HN/tegucigalpaPromo.mp4',
        profilePicture: '../../../assets/images/cities/tegus.jpg',
        postLikes: '750K',
        isLike: false,
        postComments: '300K',
        postUserName: 'Tegucigalpa',
        postDescription: 'Ciudad Capital de Honduras #ciudad',
        postSongName: 'Que horas son?',
        postSongImage: '../../../assets/images/worldIcon.png',
        isPlay: true,
        clientTikTok: "https://www.tiktok.com/@tegucigalpa",
        clientFollowers: 6000000,
        clientFollowing: 10,
        clientLocation: "Honduras",
        clientLatitude: 0,
        clientlongitude: 0,
        clientPhoneNumber:'98989999',
        clientEmail:'a@b.com'
    },

    {
        id: '3',
        videoUrl: '../../../assets/videos/Ciudad/Tegucigalpa-HN/tegucigalpaPromo.mp4',
        profilePicture: '../../../assets/images/user_profile/user_1',
        postLikes: '750K',
        isLike: false,
        postComments: '300K',
        postUserName: 'José Ramirez',
        postDescription: 'Ciudad Capital de Honduras #ciudad',
        postSongName: 'Que horas son?',
        postSongImage: '../../../assets/images/worldIcon.png',
        isPlay: true,
        clientTikTok: "https://www.tiktok.com/@tegucigalpa",
        clientFollowers: 6000000,
        clientFollowing: 10,
        clientLocation: "Honduras",
        clientLatitude: 0,
        clientlongitude: 0,
        clientPhoneNumber:'98989999',
        clientEmail:'a@b.com'
    },

    {
        id: '4',
        videoUrl: '../../../assets/videos/Ciudad/Tegucigalpa-HN/tegucigalpaPromo.mp4',
        profilePicture: '../../../assets/images/user_profile/user_2',
        postLikes: '750K',
        isLike: false,
        postComments: '300K',
        postUserName: 'Ronald Clayton',
        postDescription: 'Ciudad Capital de Honduras #ciudad',
        postSongName: 'Que horas son?',
        postSongImage: '../../../assets/images/worldIcon.png',
        isPlay: true,
        clientTikTok: "https://www.tiktok.com/@tegucigalpa",
        clientFollowers: 6000000,
        clientFollowing: 10,
        clientLocation: "Honduras",
        clientLatitude: 0,
        clientlongitude: 0,
        clientPhoneNumber:'98989999',
        clientEmail:'a@b.com'
    },

    {
        id: '5',
        videoUrl: '../../../assets/videos/Ciudad/Tegucigalpa-HN/tegucigalpaPromo.mp4',
        profilePicture: '../../../assets/images/user_profile/user_3',
        postLikes: '750K',
        isLike: false,
        postComments: '300K',
        postUserName: 'July Adagio',
        postDescription: 'Ciudad Capital de Honduras #ciudad',
        postSongName: 'Que horas son?',
        postSongImage: '../../../assets/images/worldIcon.png',
        isPlay: true,
        clientTikTok: "https://www.tiktok.com/@tegucigalpa",
        clientFollowers: 6000000,
        clientFollowing: 10,
        clientLocation: "Honduras",
        clientLatitude: 0,
        clientlongitude: 0,
        clientPhoneNumber:'98989999',
        clientEmail:'a@b.com'
    },

    {
        id: '6',
        videoUrl: '../../../assets/videos/Ciudad/Tegucigalpa-HN/tegucigalpaPromo.mp4',
        profilePicture: '../../../assets/images/user_profile/user_4',
        postLikes: '750K',
        isLike: false,
        postComments: '300K',
        postUserName: 'Reina Rodriguez',
        postDescription: 'Ciudad Capital de Honduras #ciudad',
        postSongName: 'Que horas son?',
        postSongImage: '../../../assets/images/worldIcon.png',
        isPlay: true,
        clientTikTok: "https://www.tiktok.com/@tegucigalpa",
        clientFollowers: 6000000,
        clientFollowing: 10,
        clientLocation: "Honduras",
        clientLatitude: 0,
        clientlongitude: 0,
        clientPhoneNumber:'98989999',
        clientEmail:'a@b.com'
    }
]
/*
export const GClient = [
    {
        id: parseInt(Client[Client.length].id),
        videoUrl: '../../../assets/videos/Ciudad/Tegucigalpa-HN/tegucigalpaPromo.mp4',
        profilePicture: '../../../assets/images/cities/tegus.jpg',
        postLikes: '750K',
        isLike: false,
        postComments: '300K',
        postUserName: 'Tegucigalpa',
        postDescription: 'Ciudad Capital de Honduras #ciudad',
        postSongName: 'Que horas son?',
        postSongImage: '../../../assets/images/worldIcon.png',
        isPlay: true,
        clientTikTok: "",
        clientFollowers: 0,
        clientFollowing: 0,
        clientLocation: "",
        clientLatitude: 0,
        clientlongitude: 0
    }
]
*/
